"""initial clean base configuration

Revision ID: 04788d086611
Revises: 
Create Date: 2026-06-03 22:56:29.861523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04788d086611'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('website_link', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('schema_name', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('schema_name'),
    )
    op.create_index(op.f('ix_public_companies_email'), 'companies', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_companies_email'), table_name='companies')
    op.drop_table('companies', schema='public')
    # ### end Alembic commands ###
