"""add slug to companies

Revision ID: 18c9b2212f40
Revises: de2c0620b937
Create Date: 2026-06-11 12:30:21.045630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c9b2212f40'
down_revision: Union[str, Sequence[str], None] = 'de2c0620b937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('slug', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'companies', ['slug'], schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', schema='public', type_='unique')
    op.drop_column('companies', 'slug')
    # ### end Alembic commands ###
