"""change field schema_name to nullable=True

Revision ID: de2c0620b937
Revises: 04788d086611
Create Date: 2026-06-05 11:44:34.143738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de2c0620b937'
down_revision: Union[str, Sequence[str], None] = '04788d086611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'schema_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'schema_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
