"""your message here

Revision ID: 6cd950b2b692
Revises: e43698e2ac55
Create Date: 2026-06-22 20:24:43.423121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd950b2b692'
down_revision: Union[str, Sequence[str], None] = 'e43698e2ac55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_intelligence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_summary', sa.Text(), nullable=True),
    sa.Column('target_market', sa.Text(), nullable=True),
    sa.Column('products_services', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('technology_stack', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('full_analysis', sa.Text(), nullable=True),
    sa.Column('report_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    op.create_table('company_profile_datas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('services', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('products', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('tech_stacks', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('github', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('youtube', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    if_not_exists=True
    )
    op.create_table('competitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('website_url', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('website_url'),
    if_not_exists=True
    )
    op.create_table('competitor_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=True),
    sa.Column('competitor_name', sa.String(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('services', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('products', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('tech_stacks', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('github', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('youtube', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    if_not_exists=True
    )
    op.alter_column('company_profile_datas', 'source_file',
               existing_type=sa.String(),
               nullable=True)
    

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_profile_datas', 'source_file',
               existing_type=sa.String(),
               nullable=False)
    # ### end Alembic commands ###
