"""created instagram registered company model

Revision ID: 7a1ff85ae6cf
Revises: 652f51b309fb
Create Date: 2026-07-28 11:34:35.504606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a1ff85ae6cf'
down_revision: Union[str, Sequence[str], None] = '652f51b309fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('instagram_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('follows_count', sa.Integer(), nullable=True),
    sa.Column('posts_count', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('is_business_account', sa.Boolean(), nullable=True),
    sa.Column('business_category_name', sa.String(), nullable=True),
    sa.Column('external_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analyzed_posts_count', sa.Integer(), nullable=False),
    sa.Column('total_likes', sa.Integer(), nullable=False),
    sa.Column('total_comments', sa.Integer(), nullable=False),
    sa.Column('total_video_views', sa.Integer(), nullable=False),
    sa.Column('average_likes', sa.Integer(), nullable=False),
    sa.Column('average_comments', sa.Integer(), nullable=False),
    sa.Column('average_video_views', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('content_type_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_hashtags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_mentions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_post', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_video', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latest_posts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_instagram_analysis_company_id'), 'instagram_analysis', ['company_id'], unique=False)

    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instagram_analysis_company_id'), table_name='instagram_analysis')
    op.drop_table('instagram_analysis')
    # ### end Alembic commands ###
