"""created 2 new models InstagramComparisonReport and InstagramCompetitorProfile

Revision ID: 8c176638e7f7
Revises: 7a1ff85ae6cf
Create Date: 2026-07-28 17:56:34.868352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c176638e7f7'
down_revision: Union[str, Sequence[str], None] = '7a1ff85ae6cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_comparison_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('competitor_name', sa.String(), nullable=True),
    sa.Column('engagement_gap', sa.Text(), nullable=True),
    sa.Column('content_strategy_gap', sa.Text(), nullable=True),
    sa.Column('audience_gap', sa.Text(), nullable=True),
    sa.Column('positioning_summary', sa.Text(), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_instagram_comparison_reports_company_id'), 'instagram_comparison_reports', ['company_id'], unique=False)
    op.create_index(op.f('ix_instagram_comparison_reports_competitor_id'), 'instagram_comparison_reports', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_instagram_comparison_reports_competitor_name'), 'instagram_comparison_reports', ['competitor_name'], unique=False)

    op.create_table('instagram_competitor_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('instagram_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('follows_count', sa.Integer(), nullable=True),
    sa.Column('posts_count', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('is_business_account', sa.Boolean(), nullable=True),
    sa.Column('business_category_name', sa.String(), nullable=True),
    sa.Column('external_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analyzed_posts_count', sa.Integer(), nullable=False),
    sa.Column('total_likes', sa.Integer(), nullable=False),
    sa.Column('total_comments', sa.Integer(), nullable=False),
    sa.Column('total_video_views', sa.Integer(), nullable=False),
    sa.Column('average_likes', sa.Integer(), nullable=False),
    sa.Column('average_comments', sa.Integer(), nullable=False),
    sa.Column('average_video_views', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('content_type_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_hashtags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_mentions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_post', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_video', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strongest_content_type', sa.String(), nullable=True),
    sa.Column('standout_themes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_post_insight', sa.Text(), nullable=True),
    sa.Column('notable_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_instagram_competitor_profile_competitor_id'), 'instagram_competitor_profile', ['competitor_id'], unique=False)
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
  
    op.drop_index(op.f('ix_instagram_competitor_profile_competitor_id'), table_name='instagram_competitor_profile')
    op.drop_table('instagram_competitor_profile')
    op.drop_index(op.f('ix_instagram_comparison_reports_competitor_name'), table_name='instagram_comparison_reports')
    op.drop_index(op.f('ix_instagram_comparison_reports_competitor_id'), table_name='instagram_comparison_reports')
    op.drop_index(op.f('ix_instagram_comparison_reports_company_id'), table_name='instagram_comparison_reports')
    op.drop_table('instagram_comparison_reports')
   
    # ### end Alembic commands ###
