"""lock company to public and add schema_name

Revision ID: 16837f86db73
Revises: 2e9597cdf1f1
Create Date: 2026-06-01 20:01:57.098512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16837f86db73'
down_revision: Union[str, Sequence[str], None] = '2e9597cdf1f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from alembic import context
    x_args = context.get_x_argument(as_dictionary=True)
    tenant_name = x_args.get("tenant")
    if not tenant_name:
        x_opt = context.config.get_main_option("x") if context.config else None
        if x_opt and "tenant=" in x_opt:
            for arg in x_opt.split():
                k, _, v = arg.partition("=")
                if k == "tenant":
                    tenant_name = v
                    break
    if tenant_name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('schema_name', sa.String(), nullable=False))
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.create_index(op.f('ix_public_companies_email'), 'companies', ['email'], unique=True, schema='public')
    op.create_unique_constraint(None, 'companies', ['id'], schema='public')
    op.create_unique_constraint(None, 'companies', ['schema_name'], schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', schema='public', type_='unique')
    op.drop_constraint(None, 'companies', schema='public', type_='unique')
    op.drop_index(op.f('ix_public_companies_email'), table_name='companies', schema='public')
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=True)
    op.drop_column('companies', 'schema_name')
    # ### end Alembic commands ###
